package com.lata.fsp.trackerterminal;

public interface TrackerTerminalConstants {
	public static final String LOG_DATE_FORMAT = "yyyy/MM/dd HH:mm:ss:";
	public static final String LOG_FILE_DATE_FORMAT = "yyyyMMdd";
	public static final String GPS_DATE_FORMAT = "MM/dd/yyyy HH:mm:ss";
	public static final String LOG_FILE_DIRECTORY = "/lata/logs/";
	public static final String GPS_UPDATER_LOGFILE = LOG_FILE_DIRECTORY + "gpsupdater";
	public static final String GPS_HISTORY_LOGFILE = LOG_FILE_DIRECTORY + "gpshistory";
	public static final String SEND_SOCKET_LOGFILE = LOG_FILE_DIRECTORY + "sendsocket";
	public static final String RECEIVE_SOCKET_LOGFILE = LOG_FILE_DIRECTORY + "receivesocket";
	public static final String TRACKER_TERMINAL_LOGFILE = LOG_FILE_DIRECTORY + "trackerterminal";
	public static final String LOG_FILE_EXTENSION = ".log";
	public static final String NEWLINE = "\n";
	public static final String OCTA_SERVICE_IP = "38.124.164.211";
	public static final String SERVICE_IP = OCTA_SERVICE_IP;
	public static final String GPS_RATE = "GpsRate";
	public static final String LOG = "Log";
	public static final String SERVER_IP = "ServerIP";
	public static final String DEFAULT_CAR_ID = "0000";
	public static final String FALSE = "F";
	public static final String TRUE = "T";
	public static final String CMD_ACK = "Ack";
	public static final String CMD_GET_GPS = "GetGPS";
	public static final String CMD_GET_STATE = "GetState";
	public static final String METRA_CMD_GET_STATE = "GetRunState";
	public static final String CMD_GET_VAR = "GetVar";
	public static final String CMD_REBOOT = "Reboot";
	public static final String CMD_SET_VAR = "SetVar";
	public static final String XML_COMMAND = "Command";
	public static final String XML_ID = "Id";
	public static final String XML_NAME = "Name";
	public static final String XML_STATE = "State";
	public static final String XML_CARID = "CarID";
	public static final String XML_CELLULAR_SURVEY = "Cell";
	public static final int SEND_SOCKET_PORT = 9008;
	public static final int RECEIVE_SOCKET_PORT = 9009;
	public static final int ONE_SECOND = 1000;
	public static final int FIVE_SECONDS = 5000;
	public static final int TEN_SECONDS = 10000;
	public static final int FIFTEEN_SECONDS = 15000;
	public static final int THIRTY_SECONDS = 30000;
	public static final int MAX_MSG_QUEUE_SIZE = 1000;
	public static final int MAX_DOP = 297;
	public static final int GOOD_DOP = 10;
	public static final long ID_INCREMENT = 100;
	public static final long FIFTY_MILLIS = 50;
	public static final String CLIENT_PORT = "ClientPort";
	public static final String SERVER_PORT = "ServerPort";
	
}
