#!/bin/bash

echo removing old deployment package
rm /opt/eurotech/esf/esf/packages/*lata*.dp

echo make required directories
mkdir /lata 2>/dev/null
mkdir /lata/builds 2>/dev/null
mkdir /lata/config 2>/dev/null
mkdir /lata/config/error 2>/dev/null
mkdir /lata/data 2>/dev/null
mkdir /lata/fileupdate 2>/dev/null
mkdir /lata/history 2>/dev/null
mkdir /lata/logs 2>/dev/null
mkdir /lata/transfers 2>/dev/null

chmod -R a+rw /lata/rc 2>/dev/null

echo copying /boot files...
cp -f /lata/rc/boot/grub/* /boot/grub

echo copying /etc files...
cp -f /lata/rc/etc/* /etc

echo copying /etc/rc.d/init.d files...
cp -f /lata/rc/etc/rc.d/init.d/* /etc/rc.d/init.d

echo copying known_hosts file
mkdir /root/.ssh 2>/dev/null
cp -f /lata/rc/ssh/known_hosts /root/.ssh/known_hosts
cp -f /lata/rc/ssh/manifest.txt /root/.ssh

echo copying /lata/config files...
cp -f /lata/rc/lata/config/* /lata/config

echo copying /opt files...
cp -f /lata/rc/opt/eurotech/esf/esf/* /opt/eurotech/esf/esf
cp -f /lata/rc/opt/eurotech/esf/esf/packages/* /opt/eurotech/esf/esf/packages

echo updating dpa.properties
sed -i "/.*lata.*/d" /opt/eurotech/esf/esf/dpa.properties
echo 'com.eurotech.lata.logger=file\:/opt/eurotech/esf/esf/packages/com.eurotech.lata.logger.dp' >> /opt/eurotech/esf/esf/dpa.properties

sed -i "/.*reliagate_50_21.*/d" /opt/eurotech/esf/esf/dpa.properties
echo 'com.eurotech.reliagate_50_21.io.dp=file\:/opt/eurotech/esf/esf/packages/com.eurotech.reliagate_50_21.io.dp' >> /opt/eurotech/esf/esf/dpa.properties

echo done with program files...

echo restricting access
chmod 600 /lata/config/fterm.id

echo setting execution privilages
chmod a+x /etc/rc.d/init.d/AutoUpdate
chmod a+x /etc/rc.d/init.d/GetIps
chmod a+x /etc/rc.d/init.d/GetUsage
chmod a+x /etc/rc.d/init.d/IpLogger
chmod a+x /etc/rc.d/init.d/LmtWatchDog
chmod a+x /etc/rc.d/init.d/ManifestCheck
chmod a+x /etc/rc.d/init.d/WarmUp
chmod a+x /etc/rc.d/init.d/WifiClients
chmod a+x /etc/rc.d/init.d/firewall

echo creating symbolic links...
rm /etc/rc3.d/S09WarmUp
ln -s /etc/rc.d/init.d/WarmUp /etc/rc3.d/S09WarmUp

echo setting symbolic link privileges...
chmod 777 /etc/rc3.d/S09WarmUp

echo set local time zone
ln -sf /usr/share/zoneinfo/PST8PDT /etc/localtime

echo create ftp upload file
cp -f /boot/eurotech_vector-bzImage-WR4.3.0.0_standard /lata/transfers/ftpToServerX.bin
