/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eurotech_reliagate_io_i2cbus_impl_I2cBusImpl */

#ifndef _Included_com_eurotech_reliagate_io_i2cbus_impl_I2cBusImpl
#define _Included_com_eurotech_reliagate_io_i2cbus_impl_I2cBusImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_eurotech_reliagate_io_i2cbus_impl_I2cBusImpl
 * Method:    I2CBusOpen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_eurotech_reliagate_io_i2cbus_impl_I2cBusImpl_I2CBusOpen
  (JNIEnv *, jobject);

/*
 * Class:     com_eurotech_reliagate_io_i2cbus_impl_I2cBusImpl
 * Method:    I2CBusClose
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_eurotech_reliagate_io_i2cbus_impl_I2cBusImpl_I2CBusClose
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_eurotech_reliagate_io_i2cbus_impl_I2cBusImpl
 * Method:    I2CBusWriteByte
 * Signature: (IBBB)Z
 */
JNIEXPORT jboolean JNICALL Java_com_eurotech_reliagate_io_i2cbus_impl_I2cBusImpl_I2CBusWriteByte
  (JNIEnv *, jobject, jint, jbyte, jbyte, jbyte);

/*
 * Class:     com_eurotech_reliagate_io_i2cbus_impl_I2cBusImpl
 * Method:    I2CBusWriteWord
 * Signature: (IBBS)Z
 */
JNIEXPORT jboolean JNICALL Java_com_eurotech_reliagate_io_i2cbus_impl_I2cBusImpl_I2CBusWriteWord
  (JNIEnv *, jobject, jint, jbyte, jbyte, jshort);

/*
 * Class:     com_eurotech_reliagate_io_i2cbus_impl_I2cBusImpl
 * Method:    I2CBusWriteBlock
 * Signature: (IBB[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_eurotech_reliagate_io_i2cbus_impl_I2cBusImpl_I2CBusWriteBlock
  (JNIEnv *, jobject, jint, jbyte, jbyte, jbyteArray);

/*
 * Class:     com_eurotech_reliagate_io_i2cbus_impl_I2cBusImpl
 * Method:    I2CBusReadByte
 * Signature: (IBB)B
 */
JNIEXPORT jbyte JNICALL Java_com_eurotech_reliagate_io_i2cbus_impl_I2cBusImpl_I2CBusReadByte
  (JNIEnv *, jobject, jint, jbyte, jbyte);

/*
 * Class:     com_eurotech_reliagate_io_i2cbus_impl_I2cBusImpl
 * Method:    I2CBusReadWord
 * Signature: (IBB)S
 */
JNIEXPORT jshort JNICALL Java_com_eurotech_reliagate_io_i2cbus_impl_I2cBusImpl_I2CBusReadWord
  (JNIEnv *, jobject, jint, jbyte, jbyte);

/*
 * Class:     com_eurotech_reliagate_io_i2cbus_impl_I2cBusImpl
 * Method:    I2CBusReadBlock
 * Signature: (IBB)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_eurotech_reliagate_io_i2cbus_impl_I2cBusImpl_I2CBusReadBlock
  (JNIEnv *, jobject, jint, jbyte, jbyte);

/*
 * Class:     com_eurotech_reliagate_io_i2cbus_impl_I2cBusImpl
 * Method:    I2CBusGetLastError
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_eurotech_reliagate_io_i2cbus_impl_I2cBusImpl_I2CBusGetLastError
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_eurotech_reliagate_io_i2cbus_impl_I2cBusImpl
 * Method:    I2CBusClearLastError
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_eurotech_reliagate_io_i2cbus_impl_I2cBusImpl_I2CBusClearLastError
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
