//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTC.FSP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AERecipient
    {
        public System.Guid AERecipientID { get; set; }
        public string AERecipientEmail { get; set; }
        public bool AEIsContractor { get; set; }
        public System.Guid AEReportID { get; set; }
        public System.Guid AEFrequencyID { get; set; }
        public Nullable<System.Guid> AEContractorID { get; set; }
        public System.Guid AEReportTypeID { get; set; }
    }
}
