//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTC.FSP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public System.Guid AnswerID { get; set; }
        public System.Guid QuestionID { get; set; }
        public string AnswerText { get; set; }
        public int SortOrder { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
