//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTC.FSP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appeal
    {
        public System.Guid AppealID { get; set; }
        public string AppealType { get; set; }
        public System.Guid AppealStatusID { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public System.Guid ContractorId { get; set; }
        public System.Guid Beatid { get; set; }
        public System.Guid DriverId { get; set; }
        public Nullable<int> V_ViolationId { get; set; }
        public string V_ReasonForAppeal { get; set; }
        public Nullable<int> V_BlocksGranted { get; set; }
        public Nullable<int> V_BlocksClaimed { get; set; }
        public Nullable<decimal> V_AppropriateCharge { get; set; }
        public Nullable<System.DateTime> O_Datetime { get; set; }
        public string O_CallSign { get; set; }
        public Nullable<int> O_CHPOTNumber { get; set; }
        public Nullable<int> O_NumOfBlocks { get; set; }
        public Nullable<int> O_BlocksInitGranted { get; set; }
        public string O_Detail { get; set; }
        public Nullable<System.DateTime> I_EventDate { get; set; }
        public string I_InvoiceReason { get; set; }
        public string I_AppealReason { get; set; }
        public Nullable<decimal> I_InvoiceDeduction { get; set; }
        public Nullable<decimal> I_AppealDeduction { get; set; }
        public string MTCNote { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual AppealStatu AppealStatu { get; set; }
        public virtual BeatData BeatData { get; set; }
        public virtual Contractor Contractor { get; set; }
        public virtual Driver Driver { get; set; }
    }
}
