//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTC.FSP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppealStatu
    {
        public AppealStatu()
        {
            this.Appeals = new HashSet<Appeal>();
        }
    
        public System.Guid AppealStatusID { get; set; }
        public string AppealStatus { get; set; }
    
        public virtual ICollection<Appeal> Appeals { get; set; }
    }
}
