//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTC.FSP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assist
    {
        public System.Guid AssistID { get; set; }
        public System.Guid IncidentID { get; set; }
        public System.DateTime AssistDatePosted { get; set; }
        public bool LastAssistInIncidentReport { get; set; }
        public string ProblemType { get; set; }
        public string ProblemDetail { get; set; }
        public string ProblemNote { get; set; }
        public string OtherNote { get; set; }
        public string TransportType { get; set; }
        public Nullable<double> StartODO { get; set; }
        public Nullable<double> EndODO { get; set; }
        public string DropSite { get; set; }
        public string State { get; set; }
        public string LicensePlate { get; set; }
        public string VehicleType { get; set; }
        public string OTAuthorizationNumber { get; set; }
        public string DetailNote { get; set; }
        public Nullable<double> AssistLat { get; set; }
        public Nullable<double> AssistLon { get; set; }
        public string DropSiteOther { get; set; }
        public string CallSign { get; set; }
        public Nullable<System.DateTime> TimeOnAssist { get; set; }
        public Nullable<System.DateTime> TimeOffAssist { get; set; }
        public string ActionTaken { get; set; }
        public string DropSiteBeat { get; set; }
        public string PTN { get; set; }
    }
}
