//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTC.FSP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeatData
    {
        public BeatData()
        {
            this.BeatsFreeways = new HashSet<BeatsFreeway>();
            this.Appeals = new HashSet<Appeal>();
        }
    
        public System.Guid ID { get; set; }
        public string BeatName { get; set; }
        public string BeatID { get; set; }
        public string Notes { get; set; }
        public string UserCreated { get; set; }
        public string UserModified { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public string Color { get; set; }
    
        public virtual ICollection<BeatsFreeway> BeatsFreeways { get; set; }
        public virtual ICollection<Appeal> Appeals { get; set; }
    }
}
