//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTC.FSP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeatBeatSegment
    {
        public System.Guid BeatBeatSegmentID { get; set; }
        public string BeatNumber { get; set; }
        public string BeatSegmentNumber { get; set; }
        public string ObjectID { get; set; }
    }
}
