//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTC.FSP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHPOfficer
    {
        public CHPOfficer()
        {
            this.CHPInspections = new HashSet<CHPInspection>();
        }
    
        public string BadgeID { get; set; }
        public string OfficerLastName { get; set; }
        public string OfficerFirstName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public int Id { get; set; }
    
        public virtual ICollection<CHPInspection> CHPInspections { get; set; }
    }
}
