//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTC.FSP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractorType
    {
        public ContractorType()
        {
            this.Contractors = new HashSet<Contractor>();
        }
    
        public int ContractorTypeId { get; set; }
        public string ContractorTypeName { get; set; }
    
        public virtual ICollection<Contractor> Contractors { get; set; }
    }
}
