//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTC.FSP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Freeway
    {
        public Freeway()
        {
            this.BeatsFreeways = new HashSet<BeatsFreeway>();
        }
    
        public int FreewayID { get; set; }
        public string FreewayName { get; set; }
    
        public virtual ICollection<BeatsFreeway> BeatsFreeways { get; set; }
    }
}
