//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTC.FSP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public System.Guid GroupID { get; set; }
        public string GroupName { get; set; }
        public string GroupCity { get; set; }
        public string GroupState { get; set; }
        public string GroupAddress { get; set; }
        public string GroupZip { get; set; }
        public string GroupPhone { get; set; }
        public string GroupContactName { get; set; }
    }
}
