//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTC.FSP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident
    {
        public System.Guid IncidentID { get; set; }
        public System.DateTime IncidentDatePosted { get; set; }
        public string UserPosted { get; set; }
        public string CallSign { get; set; }
        public bool FromTruck { get; set; }
        public double Lat { get; set; }
        public double Lon { get; set; }
        public bool Canceled { get; set; }
        public string ReasonCanceled { get; set; }
        public string Beat { get; set; }
        public string TruckNumber { get; set; }
        public Nullable<System.Guid> LogID { get; set; }
        public Nullable<System.Guid> WazeID { get; set; }
        public Nullable<System.Guid> TruckStatusID { get; set; }
        public string FSPLocation { get; set; }
        public string DispatchLocation { get; set; }
        public string Direction { get; set; }
        public string PositionIncident { get; set; }
        public string LaneNumber { get; set; }
        public string CHPIncidentType { get; set; }
        public Nullable<double> briefUpdateLat { get; set; }
        public Nullable<double> briefUpdateLon { get; set; }
        public string Freeway { get; set; }
        public bool BriefUpdatePosted { get; set; }
        public Nullable<System.DateTime> TimeofBriefUpdate { get; set; }
        public string CHPLogNumber { get; set; }
        public string IncidentSurveyNumber { get; set; }
        public string DriverLastName { get; set; }
        public string DriverFIrstName { get; set; }
        public Nullable<System.Guid> DriverID { get; set; }
        public Nullable<System.Guid> RunID { get; set; }
        public Nullable<System.DateTime> TimeOnIncident { get; set; }
        public Nullable<System.DateTime> TimeOffIncident { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> Acked { get; set; }
        public string CrossStreet { get; set; }
    }
}
