//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTC.FSP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectionType
    {
        public InspectionType()
        {
            this.CHPInspections = new HashSet<CHPInspection>();
        }
    
        public System.Guid InspectionTypeID { get; set; }
        public string InspectionType1 { get; set; }
        public string InspectionTypeCode { get; set; }
    
        public virtual ICollection<CHPInspection> CHPInspections { get; set; }
    }
}
