//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTC.FSP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InteractionType
    {
        public InteractionType()
        {
            this.DriverInteractions = new HashSet<DriverInteraction>();
        }
    
        public System.Guid InteractionTypeID { get; set; }
        public string InteractionType1 { get; set; }
    
        public virtual ICollection<DriverInteraction> DriverInteractions { get; set; }
    }
}
