//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTC.FSP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTC_Invoice
    {
        public MTC_Invoice()
        {
            this.MTC_Invoice_Addition = new HashSet<MTC_Invoice_Addition>();
            this.MTC_Invoice_Anomalies = new HashSet<MTC_Invoice_Anomalies>();
            this.MTC_Invoice_Deductions = new HashSet<MTC_Invoice_Deductions>();
            this.MTC_Invoice_Summary = new HashSet<MTC_Invoice_Summary>();
        }
    
        public string InvoiceID { get; set; }
        public System.Guid ContractorID { get; set; }
        public int Month { get; set; }
        public System.Guid BeatID { get; set; }
        public double FuelRate { get; set; }
        public double BaseRate { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ICollection<MTC_Invoice_Addition> MTC_Invoice_Addition { get; set; }
        public virtual ICollection<MTC_Invoice_Anomalies> MTC_Invoice_Anomalies { get; set; }
        public virtual ICollection<MTC_Invoice_Deductions> MTC_Invoice_Deductions { get; set; }
        public virtual ICollection<MTC_Invoice_Summary> MTC_Invoice_Summary { get; set; }
    }
}
