//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTC.FSP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTCActionTaken
    {
        public System.Guid MTCActionTakenID { get; set; }
        public System.Guid MTCAssistID { get; set; }
        public string ActionTaken { get; set; }
    
        public virtual MTCAssist MTCAssist { get; set; }
    }
}
