//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTC.FSP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTCIncident
    {
        public MTCIncident()
        {
            this.MTCAssists = new HashSet<MTCAssist>();
            this.MTCPreAssists = new HashSet<MTCPreAssist>();
        }
    
        public System.Guid IncidentID { get; set; }
        public System.DateTime DatePosted { get; set; }
        public string UserPosted { get; set; }
        public int fromTruck { get; set; }
        public double Lat { get; set; }
        public double Lon { get; set; }
        public bool Canceled { get; set; }
        public string Reason { get; set; }
        public string Beat { get; set; }
        public string TruckNumber { get; set; }
    
        public virtual ICollection<MTCAssist> MTCAssists { get; set; }
        public virtual ICollection<MTCPreAssist> MTCPreAssists { get; set; }
    }
}
