//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTC.FSP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTCRateTable
    {
        public System.Guid RateTableID { get; set; }
        public System.Guid BeatID { get; set; }
        public decimal CurrentMonthRate { get; set; }
        public Nullable<decimal> p100 { get; set; }
        public Nullable<decimal> p150 { get; set; }
        public Nullable<decimal> p200 { get; set; }
        public Nullable<decimal> p250 { get; set; }
        public decimal p300 { get; set; }
        public decimal p350 { get; set; }
        public decimal p400 { get; set; }
        public decimal p450 { get; set; }
        public decimal p500 { get; set; }
        public decimal p550 { get; set; }
        public Nullable<decimal> p600 { get; set; }
        public Nullable<decimal> p650 { get; set; }
        public Nullable<decimal> p700 { get; set; }
        public Nullable<decimal> p750 { get; set; }
        public Nullable<decimal> p800 { get; set; }
    }
}
