//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTC.FSP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OvertimeActivity
    {
        public System.Guid ID { get; set; }
        public System.DateTime timeStamp { get; set; }
        public string Shift { get; set; }
        public string CallSign { get; set; }
        public string OverTimeCode { get; set; }
        public Nullable<int> BlocksApproved { get; set; }
        public string Beat { get; set; }
        public string Contractor { get; set; }
        public Nullable<bool> Confirmed { get; set; }
    }
}
