//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTC.FSP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostedSurvey
    {
        public System.Guid PostedSurveyID { get; set; }
        public System.Guid SurveyID { get; set; }
        public System.DateTime PostDate { get; set; }
    
        public virtual Survey Survey { get; set; }
    }
}
