//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTC.FSP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Answers = new HashSet<Answer>();
            this.SurveysQuestions = new HashSet<SurveysQuestion>();
        }
    
        public System.Guid QuestionID { get; set; }
        public string QuestionText { get; set; }
        public System.Guid QuestionTypeID { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual QuestionType QuestionType { get; set; }
        public virtual ICollection<SurveysQuestion> SurveysQuestions { get; set; }
    }
}
