//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTC.FSP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public System.Guid ReportID { get; set; }
        public string ReportName { get; set; }
        public string ConnString { get; set; }
        public string SQL { get; set; }
        public string cmdType { get; set; }
        public string parameters { get; set; }
    }
}
