//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTC.FSP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survey
    {
        public Survey()
        {
            this.PostedSurveys = new HashSet<PostedSurvey>();
            this.SurveysQuestions = new HashSet<SurveysQuestion>();
        }
    
        public System.Guid SurveyID { get; set; }
        public string SurveyName { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime DateModified { get; set; }
        public string SurveyNotes { get; set; }
        public string SurveyBoilerplate { get; set; }
    
        public virtual ICollection<PostedSurvey> PostedSurveys { get; set; }
        public virtual ICollection<SurveysQuestion> SurveysQuestions { get; set; }
    }
}
