//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTC.FSP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TowTruckSetup
    {
        public string MountedSecurely { get; set; }
        public string ConnectedToCell { get; set; }
        public string DCPowerConnected { get; set; }
        public string RouterUnitMountedSecurely { get; set; }
        public string MoistureFree { get; set; }
        public string Speedtest { get; set; }
        public string GPSSentProperly { get; set; }
        public string InstallerName { get; set; }
        public System.DateTime InstallationDate { get; set; }
        public string TowTruckCompany { get; set; }
        public string VehicleID { get; set; }
        public string SystemSerialNumber { get; set; }
        public string IPAddress { get; set; }
        public string UploadSpeed { get; set; }
        public string DownloadSpeed { get; set; }
    }
}
