//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTC.FSP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TowTruckYard
    {
        public System.Guid TowTruckYardID { get; set; }
        public string Location { get; set; }
        public string Comments { get; set; }
        public string TowTruckYardNumber { get; set; }
        public string TowTruckYardDescription { get; set; }
        public string TowTruckCompanyName { get; set; }
        public string TowTruckCompanyPhoneNumber { get; set; }
        public System.Data.Entity.Spatial.DbGeography Position { get; set; }
    }
}
