//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTC.FSP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TruckAlert
    {
        public System.Guid AlertID { get; set; }
        public string DriverName { get; set; }
        public string ContractorCompany { get; set; }
        public string Beat { get; set; }
        public string AlertName { get; set; }
        public System.DateTime AlertStart { get; set; }
        public Nullable<System.DateTime> AlertEnd { get; set; }
        public Nullable<int> AlertMins { get; set; }
        public string TruckNumber { get; set; }
        public Nullable<double> lat { get; set; }
        public Nullable<double> lon { get; set; }
        public Nullable<System.Guid> runID { get; set; }
        public Nullable<System.DateTime> ExcuseTime { get; set; }
        public Nullable<System.DateTime> DismissTime { get; set; }
        public string ExcusedBy { get; set; }
        public string Comment { get; set; }
        public string location { get; set; }
        public Nullable<double> Speed { get; set; }
        public string Heading { get; set; }
        public string CallSign { get; set; }
        public Nullable<System.Guid> ScheduleID { get; set; }
        public Nullable<int> ScheduleType { get; set; }
    }
}
