//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTC.FSP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Var
    {
        public System.Guid VarID { get; set; }
        public string VarName { get; set; }
        public string VarValue { get; set; }
        public string Description { get; set; }
        public string Units { get; set; }
        public Nullable<bool> IsMTCAlarm { get; set; }
        public string FriendlyVarName { get; set; }
    }
}
