//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTC.FSP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAZEData
    {
        public System.Guid WazeID { get; set; }
        public bool Direction { get; set; }
        public string SentTo { get; set; }
        public string SentFrom { get; set; }
        public string SentBy { get; set; }
        public System.DateTime timeStamp { get; set; }
        public string wazeRawData { get; set; }
    }
}
