//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTC.FSP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAZEIncoming
    {
        public string UUID { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> PubDate { get; set; }
        public string Type { get; set; }
        public string SubType { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Lon { get; set; }
        public Nullable<int> RoadType { get; set; }
        public Nullable<int> Reliability { get; set; }
        public Nullable<int> nThumbsUp { get; set; }
        public Nullable<int> Confidence { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string Segment { get; set; }
        public string DispatchedTo { get; set; }
        public Nullable<System.DateTime> DispatchTime { get; set; }
        public Nullable<bool> Accepted { get; set; }
        public Nullable<System.DateTime> AckTime { get; set; }
        public string AckMessage { get; set; }
    }
}
