#!/bin/bash
###############################################################
lmtip=$(ifconfig | grep "P-t-P" | sed 's/.*:\([0-9]*\.[0-9]*\.[0-9]*\.[0-9]*\).*P.*/\1/');
cat /lata/logs/ips*.log | grep "$lmtip >" | sed -ne 's/.*> \([0-9]*\.[0-9]*\.[0-9]*\.[0-9]*\):.*/\1/p' | sort -u > /lata/logs/iplist.log
